### ISSUE TITLE
Dynamic Liferay user database connection

### ISSUE THREAD

**Issue by jmbarcial** [sdcc-i-coop-portal/zoom09#11]

**Comment by regiboy** [comment]
If previously logged on by a recognized postgresql user, then a not-recognized user tries to connect,
nakaka-lusot siya.

**Comment by regiboy** [comment]
* If connection is not nulll, if attempting another connection (from another user), connection does not set to null upon exception. Fixed now.

**Comment by regiboy** [comment]
Tentative:
* set DbConnection.userName: from **User.screenName** to **User.userid** (prepared na ito)

**Comment by regiboy** [comment]
Ok since 2017-12-13.
